[tools]
hk = { version = "1.54.1", postinstall = "hk install --mise" }
betterleaks = "1.7.3"
cocogitto = "7.0.0"
actionlint = "1.7.12"
zizmor = "1.29.0"
go = "1.26.5"
golangci-lint = "2.12.2"
goreleaser = "2.17.1"

[settings]
lockfile = true
locked = true
